project:
  type: website
  output-dir: docs

website:
  title: "Lingyuan Meng"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - text: Blog
        href: blog/index.qmd

sidebar:
  - title: "Blog"
    style: "docked"
    search: false
    contents:
      - blog/index.qmd
      - blog/ab-testing-call-to-action.qmd
      - blog/hw2-card-krueger.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

